# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEEucz9kikjH0bVsNmu37JXc3CPFW_iY

**Day** **1**
"""

print("Hello world",7,"Bindu")
print(5)
print(20*20)

"""comments,escape sequences

"""

# new line
'''ths is a multiline comment
you know'''
"""this is also a multi line
comment"""
print("this is previous line\nthis is a next line") #contionus comment
print("She is the \"lawyer\"")

"""Separator,end

"""

print("Hey",6,7,sep="-")
print("Hey",6,7,sep="-",end="***")

"""Variables,Data Types

"""

a=1232,
a1=12.2
a2=complex(8,2)
print(type(a),type(a1),type(a2))
b="Bindu Samala"
print(type(b))
c=True
print(type(c))
d=None
print(type(d))
print(a,b,c,d)

#list is a collection of data elements of different types and list is mutable
l1=[5,"bindu",[2,3,4],["hey","hi"]]
print(l1)
print(type(l1))
#tuple is immutable
t1=("Hi","hello",1,"Hi")
print(t1)
#dictionary
d1={"name":"Bindu","college":"NITRR","instittue":9}
print(d1)

"""Operators

"""

print(10+2) #addition
print(10-2) #subtraction
print(10*2) #multiplication
print(11/2) #division
print(11//2)  #floor division
print(11%2) #modulus
print(2**5) #exponentiation

"""TypeCasting"""

# str() int() float() hext() oct() list() tuple() #dict set() ord()
a="26"
b=2
print(int(a)+b) #explicit typecasting
c=1.9
d=8
print(c+d)#implicit type casting gives float

"""User Input"""

# a=input("Enter your name")
# print(a)
b=int(input())
c=float(input())
print(b+c)